spring.application.name=module_3_async_service_a
server.port=8082

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=lab-3-1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.concurrency=3

spring.sql.init.mode=always
spring.datasource.username=lab_user
spring.datasource.password=lab_pass
spring.datasource.url=jdbc:postgresql://localhost:5441/lab_db
spring.kafka.listener.ack-mode=batch
#spring.kafka.listener.ack-mode=manual
#logging.level.org.springframework.kafka=DEBUG

spring.kafka.consumer.properties.max.poll.interval.ms=10000
spring.kafka.consumer.properties.max.poll.records=3