CREATE  TABLE IF NOT EXISTS orders (
   id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   userId INT NOT NULL,
   productId INT NOT NULL,
   quantity INT NOT NULL,
   status VARCHAR NOT NULL DEFAULT 'Pending'
);


CREATE TABLE IF NOT EXISTS inventory (
     id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     productId INT NOT NULL,
     stock INT NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    orderId INT NOT NULL,
    amount NUMERIC NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'Pending'
);