services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # This extra_hosts line is CRITICAL for Linux users to make host.docker.internal work
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab_user -d lab_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:latest
    container_name: toxiproxy
    ports:
      - "8474:8474"   # Toxiproxy API
      - "18080:18080" # Proxy for service_a
      - "18081:18081" # Proxy for service_b
      - "18082:18082" # Proxy for service_c
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7
    container_name: jv-redis
    ports:
      - "6379:6379"
    volumes:
      - jv_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  jv_redis_data: