# Connecting through PG Bouncer
spring.datasource.url=jdbc:postgresql://lab2_pgbouncer:5432/lab_db

# Connecting directly to PG
#spring.datasource.url=jdbc:postgresql://lab2_postgres:5432/lab_db


spring.sql.init.mode=never
