spring.sql.init.mode=never

datasource.shard0.url=jdbc:postgresql://localhost:5441/lab_db
datasource.shard1.url=jdbc:postgresql://localhost:5442/lab_db
datasource.shard2.url=jdbc:postgresql://localhost:5443/lab_db
datasource.shard3.url=jdbc:postgresql://localhost:5444/lab_db

#migration.state=stable