spring.application.name=service_b
server.port=8081
services.c.url=http://localhost:8082
# services.c.url=http://localhost:18082
management.endpoints.web.exposure.include=health,metrics,prometheus


management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
# Jaeger only supports traces, not metrics - disable OTLP metrics export to avoid 404
management.otlp.metrics.export.enabled=false

